baseURL = "/"
languageCode = "en-us"
title = "Chance's Sketchpad"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Chance Jiajie Li"
description = "Graduate Student @mitmedialab | prev @MicrosoftResearch @civic-data-design-lab"
company = "Massachusetts Institute of Technology"
CompanyURL = "https://mit.edu/"
github = "LeeJAJA"
linkedin = "chanceli"
email = "jiajie@mit.edu"
url = "https://jiajie.media/"
keywords = "MIT, MAS.863, How To Make (almost) Anything 2023"
rss = true
lastmod = true
userStatusEmoji = "😀"
favicon = "/images/favicon.ico"
location = "Neil's Class"
locationURL = "https://fab.cba.mit.edu/classes/863.23/"
enableGitalk = true

[params.gitalk]
clientID = "Your client ID"
clientSecret = "Your client secret"
repo = "repo"
owner = "MeiK2333"
admin = "MeiK2333"
id = "location.pathname"
labels = "gitalk"
perPage = 15
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false


[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
unsafe = true
